#!/bin/bash

#Update env variables

echo http_proxy=${EGRESS_URL} >> /etc/environment
echo https_proxy=${EGRESS_URL} >> /etc/environment
echo ftp_proxy=${EGRESS_URL} >> /etc/environment
echo HTTP_PROXY=${EGRESS_URL} >> /etc/environment
echo HTTPS_PROXY=${EGRESS_URL} >> /etc/environment
echo FTP_PROXY=${EGRESS_URL} >> /etc/environment
echo no_proxy=169.254.169.254,localhost,127.0.0.1 >> /etc/environment
echo NO_PROXY=169.254.169.254,localhost,127.0.0.1 >> /etc/environment

for line in $( cat /etc/environment ) ; do export $line ; done

#update ssm config
sed -i '/exec \/usr\/bin\/amazon-ssm-agent/d' /etc/init/amazon-ssm-agent.conf
echo env http_proxy=${EGRESS_URL} >> /etc/init/amazon-ssm-agent.conf
echo env https_proxy=${EGRESS_URL} >> /etc/init/amazon-ssm-agent.conf
echo env HTTP_PROXY=${EGRESS_URL} >> /etc/init/amazon-ssm-agent.conf
echo env HTTPS_PROXY=${EGRESS_URL} >> /etc/init/amazon-ssm-agent.conf
echo env no_proxy=169.254.169.254,localhost,127.0.0.1 >> /etc/init/amazon-ssm-agent.conf
echo "exec /usr/bin/amazon-ssm-agent" >> /etc/init/amazon-ssm-agent.conf

stop amazon-ssm-agent
start amazon-ssm-agent
