node {
  withCredentials([string(credentialsId: 'L7ClientKey', variable: 'CLIENT_KEY'),string(credentialsId: 'L7ClientSecret', variable: 'CLIENT_SECRET')]) {
  stage('Clone repository') {
    checkout scm
  }
  stage('LaunchKafka') {
    dir('install'){
    sh 'sh ./launchKafka.sh'
    }
    }
  stage('Verify Service is Up') {
    dir('install'){
    sh 'sh ./isServiceUp.sh'
    }
  }
}
}
