FROM docker.optum.com/bdp_tech/python:3.5.5_alphine

RUN pip install --no-cache-dir dash==0.21.1 \
                                dash-renderer==0.13.0  \
                                dash-html-components==0.11.0   \
                                dash-core-components==0.24.0  && \
    pip install --no-cache-dir  plotly --upgrade
