apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: default-user 
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: 'MustRunAs'
    ranges:
    - min: 1
      max: 65535
  supplementalGroups:
    rule: 'MustRunAs'	
    ranges:
    - min: 1
      max: 65535 
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'downwardAPI'
  - 'persistentVolumeClaim'
  - 'glusterfs'
  - 'iscsi'
  - 'flexVolume'
  - 'secret'
  allowedFlexVolumes:
  - driver: 'mapr.com/maprfs'
