apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: super-user-policyrole
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - extensions
  resourceNames:
  - super-user 
  resources:
  - podsecuritypolicies
  verbs:
  - use
