apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: super-user 
spec:
  privileged: true
  allowPrivilegeEscalation: true 
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'downwardAPI'
  - 'persistentVolumeClaim'
  - 'glusterfs'
  - 'iscsi'
  - 'flexVolume'
  - 'secret'
  allowedFlexVolumes:
  - driver: 'mapr.com/maprfs'
