# Base image
FROM openjdk:8-jdk-alpine

RUN mkdir -p /usr/app/

# Adds properties file
ADD apicatalog.json /apicatalog.json

COPY ./target/${artifactId}-0.0.1-SNAPSHOT.jar /usr/app

WORKDIR /usr/app
EXPOSE 8080

USER 1001

CMD ["java","-jar","${artifactId}-0.0.1-SNAPSHOT.jar"]
