version: 0.0
os: linux
files:
  - source: squid
    destination: /etc/squid
permissions:
  - object: /etc/squid
    pattern: "**"
    owner: "squid"
    group: "squid"
    mode: 644
    type:
      - directory
hooks:
  BeforeInstall:
    - location: scripts/remove-squid-conf.sh
      timeout: 10
      runas: root
  AfterInstall:
    - location: scripts/rename-squid-conf.sh
      timeout: 10
      runas: root
  ApplicationStart:
    - location: scripts/reload-squid.sh
      timeout: 30
      runas: root
