#!/bin/bash -ex 

function super_curl(){
	local url=$1
	local file="${url##*/}"
	if ! curl -f --ipv4 -Lo "/tmp/${file}" --connect-timeout 20 --retry 5 --retry-delay 10 "${url}"; then
        echo "== Failed to download ${url}. Retrying. =="
    else
          echo "== Downloaded ${file} =="
    fi
}

# Install SSM agent. 
#super_curl "https://amazon-ssm-us-east-1.s3.amazonaws.com/latest/linux_amd64/amazon-ssm-agent.rpm"
#sudo yum install -y /tmp/amazon-ssm-agent.rpm 
#rm /tmp/amazon-ssm-agent.rpm 

#prep  
sudo mkdir -p /home/ec2-user/workspace/ 

# install packer
super_curl "https://releases.hashicorp.com/packer/1.3.1/packer_1.3.1_linux_amd64.zip"
unzip /tmp/packer_1.3.1_linux_amd64.zip -d /home/ec2-user/workspace/
sudo ln -s /home/ec2-user/workspace/packer  /usr/bin/packer.io
packer.io -v 

#Download artifacts from S3
bucket=`aws s3 ls | grep packer-artifacts-* | awk '{ print $3 }'`
aws s3 cp s3://${bucket}/ami.zip /home/ec2-user/workspace/
unzip /home/ec2-user/workspace/ami.zip -d /home/ec2-user/workspace/

