#!/bin/bash

bucket=`aws s3 ls | grep packer-artifacts-* | awk '{ print $3 }'`

#Get subnet id from metadata endpoint
export SUBNET_ID=`curl -s http://169.254.169.254/latest/meta-data/network/interfaces/macs/$(curl -s http://169.254.169.254/latest/meta-data/network/interfaces/macs/)subnet-id`

packer.io build -color=false -var-file=/home/ec2-user/workspace/ubuntu_var.json /home/ec2-user/workspace/packer.json 2>&1 | sudo tee /home/ec2-user/workspace/output_ubuntu.txt

aws s3 cp /home/ec2-user/workspace/output_ubuntu.txt s3://${bucket}/

echo "Complete Ubuntu build"

packer.io build -color=false -var-file=/home/ec2-user/workspace/amazon_linux2_eks_var.json /home/ec2-user/workspace/packer.json 2>&1 | sudo tee /home/ec2-user/workspace/output_eks.txt

aws s3 cp /home/ec2-user/workspace/output_eks.txt s3://${bucket}/

echo "Complete EKS image build"

packer.io build -color=false -var-file=/home/ec2-user/workspace/amazon_linux2_egress_proxy_var.json /home/ec2-user/workspace/packer.json 2>&1 | sudo tee /home/ec2-user/workspace/output_egress_proxy.txt

aws s3 cp /home/ec2-user/workspace/output_egress_proxy.txt s3://${bucket}/

echo "Complete egress proxy image build"