#!/bin/bash

stackname=${egress_proxy_name}
loggroup=${cloudwatch_logs_group}
log_region=${cloudwatch_region}

if [ -z $stackname ] || [ -z $loggroup ] || [ -z $log_region ]; then
	echo "Missing arguments"
	exit 1
fi

cd /home/ec2-user
yum update -y

if [[ `systemctl list-units|grep -c awslogs.service` == 1 ]];then
  azzone=`curl -s 169.254.169.254/latest/meta-data/placement/availability-zone`
  region=$${azzone::-1}
  sed -i "s/^region = .*/region = $region/" /var/awslogs/etc/aws.conf
  sed -i "s/egress-proxy-logs/$loggroup/" /var/awslogs/etc/awslogs.conf
  systemctl restart awslogs.service
fi

sed -i "s/LOG_REGION/$log_region/g" /home/ec2-user/squid-metrics.sh
sed -i "s/STACK_NAME/$stackname/g" /home/ec2-user/squid-metrics.sh