#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )

FROM        docker.optum.com/cloudscaffolding/python:3
EXPOSE      8080
ADD         . /code
WORKDIR     /code
RUN         pip install --no-cache-dir -r requirements.txt
ENTRYPOINT ["uwsgi", "--http", "0.0.0.0:8080", "--module", "wsgi:application", "--processes", "1", "--threads", "8"]
