apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      app: ose-icp-app
    name: ose-cm-bifrost
    namespace: ace-devops-dev
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: 'docker.optum.com/scarlso8/ose-cm-bifrost:latest'
      generation: 1
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      app: ose-icp-app
    name: ose-cm-jboss
    namespace: ace-devops-dev
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: 'docker.optum.com/scarlso8/ose-cm-jboss:latest'
      generation: 1
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-icp
    namespace: ace-devops-dev
  spec:
    paused: true
    replicas: 0
    revisionHistoryLimit: 10
    selector:
      app: ose-icp-app
      deploymentconfig: ose-cm-icp
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ose-icp-app
          deploymentconfig: ose-cm-icp
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: icp-configmap
          image: 'docker.optum.com/scarlso8/ose-cm-bifrost:latest'
          imagePullPolicy: Always
          name: ose-cm-bifrost
          ports:
          - containerPort: 9191
            protocol: TCP
          - containerPort: 9197
            protocol: TCP
          - containerPort: 9199
            protocol: TCP
          resources:
            limits:
              memory: 1G
            requests:
              memory: 1G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /usr/share/optum/icp/ImportFiles
            name: cm-icp-importfiles
          - mountPath: /usr/share/optum/icp/KB_Extracts
            name: cm-icp-kbextracts
          - mountPath: /usr/share/optum/icp/LCD_Extracts
            name: cm-icp-lcdextracts
          - mountPath: /usr/share/optum/icp/log
            name: cm-icp-log
        - envFrom:
          - configMapRef:
              name: icp-configmap
          image: 'docker.optum.com/scarlso8/ose-cm-jboss:latest'
          imagePullPolicy: Always
          name: ose-cm-jboss
          ports:
          - containerPort: 25
            protocol: TCP
          - containerPort: 3528
            protocol: TCP
          - containerPort: 3529
            protocol: TCP
          - containerPort: 4712
            protocol: TCP
          - containerPort: 4713
            protocol: TCP
          - containerPort: 8009
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 9443
            protocol: TCP
          - containerPort: 9990
            protocol: TCP
          - containerPort: 9999
            protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /cm/app
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 7G
            requests:
              memory: 7G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /usr/share/optum/icp/ImportFiles
            name: cm-icp-importfiles
          - mountPath: /usr/share/optum/icp/KB_Extracts
            name: cm-icp-kbextracts
          - mountPath: /usr/share/optum/icp/LCD_Extracts
            name: cm-icp-lcdextracts
          - mountPath: /usr/share/optum/icp/log
            name: cm-icp-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: cm-icp-importfiles
          persistentVolumeClaim:
            claimName: cm-importfiles
        - name: cm-icp-lcdextracts
          persistentVolumeClaim:
            claimName: cm-lcdextracts
        - name: cm-icp-log
          persistentVolumeClaim:
            claimName: cm-log
        - name: cm-icp-kbextracts
          persistentVolumeClaim:
            claimName: cm-kbextracts
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ose-cm-bifrost
        from:
          kind: ImageStreamTag
          name: 'ose-cm-bifrost:latest'
          namespace: ace-devops-dev
        lastTriggeredImage: >-
          docker.optum.com/scarlso8/ose-cm-bifrost:latest
      type: ImageChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ose-cm-jboss
        from:
          kind: ImageStreamTag
          name: 'ose-cm-jboss:latest'
          namespace: ace-devops-dev
        lastTriggeredImage: >-
          docker.optum.com/scarlso8/ose-cm-jboss:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-icp-9191
  spec:
    host: ose-cm-icp-9191-ace-devops-dev.ocp-elr-core-nonprod.optum.com
    port:
      targetPort: 9191-tcp
    to:
      kind: Service
      name: ose-cm-icp-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-icp-9197
  spec:
    host: ose-cm-icp-9197-ace-devops-dev.ocp-elr-core-nonprod.optum.com
    port:
      targetPort: 9197-tcp
    to:
      kind: Service
      name: ose-cm-icp-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-icp-9199
  spec:
    host: ose-cm-icp-9199-ace-devops-dev.ocp-elr-core-nonprod.optum.com
    port:
      targetPort: 9199-tcp
    to:
      kind: Service
      name: ose-cm-icp-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-icp-25
  spec:
    host: ose-cm-icp-25-ace-devops-dev.ocp-elr-core-nonprod.optum.com
    port:
      targetPort: 25-tcp
    to:
      kind: Service
      name: ose-cm-icp-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-icp-3528
  spec:
    host: ose-cm-icp-3528-ace-devops-dev.ocp-elr-core-nonprod.optum.com
    port:
      targetPort: 3528-tcp
    to:
      kind: Service
      name: ose-cm-icp-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-icp-3529
  spec:
    host: ose-cm-icp-3529-ace-devops-dev.ocp-elr-core-nonprod.optum.com
    port:
      targetPort: 3529-tcp
    to:
      kind: Service
      name: ose-cm-icp-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-icp-4712
  spec:
    host: ose-cm-icp-4712-ace-devops-dev.ocp-elr-core-nonprod.optum.com
    port:
      targetPort: 4712-tcp
    to:
      kind: Service
      name: ose-cm-icp-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-icp-4713
  spec:
    host: ose-cm-icp-4713-ace-devops-dev.ocp-elr-core-nonprod.optum.com
    port:
      targetPort: 4713-tcp
    to:
      kind: Service
      name: ose-cm-icp-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-icp-8009
  spec:
    host: ose-cm-icp-8009-ace-devops-dev.ocp-elr-core-nonprod.optum.com
    port:
      targetPort: 8009-tcp
    to:
      kind: Service
      name: ose-cm-icp-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-icp-8080
  spec:
    host: ose-cm-icp-ace-devops-dev.ocp-elr-core-nonprod.optum.com
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ose-cm-icp-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-icp-8443
  spec:
    host: ose-cm-icp-8443-ace-devops-dev.ocp-elr-core-nonprod.optum.com
    port:
      targetPort: 8443-tcp
    to:
      kind: Service
      name: ose-cm-icp-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-icp-9443
  spec:
    host: ose-cm-icp-9443-ace-devops-dev.ocp-elr-core-nonprod.optum.com
    port:
      targetPort: 9443-tcp
    to:
      kind: Service
      name: ose-cm-icp-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-icp-9990
  spec:
    host: ose-cm-icp-9990-ace-devops-dev.ocp-elr-core-nonprod.optum.com
    port:
      targetPort: 9990-tcp
    to:
      kind: Service
      name: ose-cm-icp-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-icp-9999
  spec:
    host: ose-cm-icp-9999-ace-devops-dev.ocp-elr-core-nonprod.optum.com
    port:
      targetPort: 9999-tcp
    to:
      kind: Service
      name: ose-cm-icp-service
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-icp-service
  spec:
    ports:
    - name: 25-tcp
      port: 25
      protocol: TCP
      targetPort: 25
    - name: 3528-tcp
      port: 3528
      protocol: TCP
      targetPort: 3528
    - name: 3529-tcp
      port: 3529
      protocol: TCP
      targetPort: 3529
    - name: 4712-tcp
      port: 4712
      protocol: TCP
      targetPort: 4712
    - name: 4713-tcp
      port: 4713
      protocol: TCP
      targetPort: 4713
    - name: 8009-tcp
      port: 8009
      protocol: TCP
      targetPort: 8009
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 9443-tcp
      port: 9443
      protocol: TCP
      targetPort: 9443
    - name: 9990-tcp
      port: 9990
      protocol: TCP
      targetPort: 9990
    - name: 9999-tcp
      port: 9999
      protocol: TCP
      targetPort: 9999
    - name: 9191-tcp
      port: 9191
      protocol: TCP
      targetPort: 9191
    - name: 9197-tcp
      port: 9197
      protocol: TCP
      targetPort: 9197
    - name: 9199-tcp
      port: 9199
      protocol: TCP
      targetPort: 9199
    selector:
      deploymentconfig: ose-cm-icp
    sessionAffinity: None
    type: ClusterIP
  status: {}
kind: List
metadata: {}