apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rb-employee-nsr
subjects:
- kind: ServiceAccount
  namespace: development
  name:rbacdev
roleRef:
  kind: ClusterRole
  name: namespace-read 
  apiGroup: rbac.authorization.k8s.io
