apiVersion: v1
kind: Pod
metadata:
  name: pod-iscsi-chap-lun-1
  namespace: ns-iscsi1
spec:
  containers:
  - name: busybox-1
    image: busybox
    args:
    - sleep
    - "1000000"
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /data-1
      name: iscsi-vol
  volumes:
    - name: iscsi-vol
      persistentVolumeClaim:
        claimName: iscsi-pvc-chap-lun-1

