hub:
  db:
    type: sqlite-memory
  image:
    name: docker.optum.com/bd_docid/jupyterhub
    tag: centoshub8
    imagePullPolicy: Always
  extraConfig: |
    c.JupyterHub.log_level = 'DEBUG'
auth:
  type: custom
  custom:
    className: ldapauthenticator.LDAPAuthenticator
    config:
      server_address: "ad-ldap-prod.uhc.com"
      use_ssl: False
      bind_dn_template: "MS\\{username}"
      user_attribute: "sAMAccountName"
      user_search_base: "DC=ms,DC=ds,DC=uhc,DC=com"
      lookup_dn: True
      lookup_dn_search_user: "cn=<USER>,ou=Unix,ou=ServiceAccounts,ou=UHT,ou=UHG,dc=ms,dc=ds,dc=uhc,dc=com"
      lookup_dn_search_password: "<PASSWORD>"
      allowed_groups: ['CN=<GROUP>,CN=Users,DC=ms,DC=ds,DC=uhc,DC=com']
proxy:
  secretToken: a5c4cdc82c867913e410b1c532f62f95a4cec5d6e01b5c2d230142d7eef20f29
  service:
    nodePorts:
      https: 32713 
  https:
    enabled: true
    type: manual
    manual:
      key: |
        -----BEGIN PRIVATE KEY-----
        MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDrA7W7b5BU0P8z
        jxttoCaXRftzpnPEI9hetW1+kiIhvb5EXZdw8sePNGY7YtKpc0453n3rFdx5AC9I
        kxgeBgP/5Rj0DtLqNl86m3fQqRmvfchzegwk62e8wu7SOYEX2URNwu6V/YIUeM4W
        5EPS8x+nmLAzCiwcnJHqSpath9CC+Q+XyrkIPPDU+kaAvxlc5+1s0O7OFfwwmNPT
        tmP8gJB6WLmlK3MQpWX2N8KRfkDbvDZkW/QA2266zg6f7saOM3xcY/CogO0AE6De
        D/Lcc6xSB1+QN3So9auiDU7wMzJA21oz4Ayqzowa1oseYlSm++pwP6t5+KCQZjCo
        8kzAw0naVdBw7nSHnGfFVc3xSy8tbRJeG2of0kkP0oKqM0t789v9mj8OLbdfqt1j
        TD1qXku1t9m4NIuzT/A2pPm618KKzCBs/c3jGIQI7H6JouJrkuZm6cXCWZJUR7/s
        Im8QNN0yDg+TQ5v/OxHQA25b9ddPGU7K/D8xDiElbum2C2aQ+2CyBwBSAzueXC12
        IORX1kGxmzPmnDdQs+fNV7LKDlXSw8BxidiE6YIurqzYrXrjAYUflPO4P1KHHl2C
        3DITxDlkVrZ16RqSr31VVpWGuraQYBACIP8THJ7QvHZKraVuW0KVOQELEJ4ctGnb
        5Pdz+swiAJ+AKvEDpzw11n25u33ddwIDAQABAoICAAra0gMFRSJVwOPNwVOP6Rhl
        mBagYop1qWG+eX82GrN6QxZ/SCZkYElB/1LQ3rAK7lsH5sL78IH6OzTb7mo8luSz
        3TIwmRdOSZm4YpFVriUH50FGKtdttA3o5wT4uPi0BU6eKUzuN5rgdYxjIKrWpeik
        ycahuqXbqXWr2kfLlRrnjAvTxjYWMn1zzdvWd8Jtx+6Vu+Hy7AIGnQoTS4z3FzU/
        cduqJRdovEviCW+U6EP97nk2Mg/0Eqo4KD7E1ZDt2dmemBgAVHIDdhOroukBwrzL
        MGPF2/KN3k6O1M2NX83VE9Z/i7Y78gavUB+oJQbNbeefWTk5/ZiNz8ON5XOl0XxY
        fCCqZRCTfR/CzoA+yHLOmSvxEmcNi+y8aeNrjZqgI0PkAmn21rzuUFXEVaKiYgpF
        Z6Rk4uZzgZJxVF0q86LDnB5+OuvhFklOL8Il6HCFYFz+GquiA1fwQP8hXl/VxADb
        dKm4YQijZOT3FqKBW3Oht2fKHAoA8y98giuZo+b5AK/M7LO8ZBygr+q++PqX1sDN
        3bvtaXQFMK4f+JdsgO9bnigYasB1NaH3NeOoJr0GpMMrhQsk7IZeFY3OdzipYG1I
        O9GSZhTHXC6Wu2EtbdzJwgc47GCeBOJGrkeX07/1T4pOtZzoqIYUZ4wc4qyG5HyK
        CTZwJ4tXB6gSaPZWnGNxAoIBAQD+JX+HaaE5gztSToF1kTTz7t3LIAvuCU2GDHfX
        QAuaG1AuW3mgUwGiwJxxtlUnjOJ3q62bsUVgeGWmTutKhoHZ2eWb+WqvidiXWlNb
        UQYMlR3afBLXgOQjUmfjv+AyQwDPBy1aaXkPqwgnebOH99Rq8gJrQ8o1G7ytEVpL
        h0mRumUT8sxQ1L4+RAG27CUQZXI0HkQnnQR0gRSsOFnyROLJakCfK4fiCiwYAYsm
        B7JZ5d1jOQsLAAXZeJjyjZKHdjpGc+0j15TplLXNN9faeNJojuZnKc9TeWk/Qs83
        soCGLQCk3iUx6P2aQLDqBEwMyH+YJpizYEDS0BYFPBDuJ4dPAoIBAQDsun3VLalc
        6diWSv9p+4rHdE564ndaUE+svJMoSNK62cr/nF9ra1JbOXCeMZVBLOIDYTl9bU2C
        iX8Ne9TEuwB36NBsSCflicJZR7Q8Ws+tp0ObiXmpkLkpgfNXgYBXhsXM/EoVR8AQ
        t1j8jMDJYjqPqNsLSbS9WZswKAQmE9S9qJnGGjyeXwI3aBt0Do/m+70b8FsQb+QA
        FP98eul2cYfSoPomZYkVgAeXcUwsKcQzcBVDN7PjaikX6I8/52QCZmrf4EcfyIQJ
        UOevFnsiSebujiJTnoA4p4kvhE9jvKbfBYtBLYBx6T14PJNj7ARcjIUvvs4mH7sV
        zAVBkMFy3j1ZAoIBAQDqfUaxdjCflAnD41NnWlb1Ssuxgxv+wO6aZB6eqCUMR28v
        lo8d8fhsZjLyaD0hhMffirNgF6vfWrbPP7mwxXJBwt4rj3F0DUeePmTyuEtQiLVG
        xXvNAst8G6hnZr5BIbk5S3H5HZ/paPDZG10ecve2xRyeQ6nqXnEzbfNWBLlIkCZ6
        xWbmnaP6Z1z9ndyEyFUa6WIQ+rsFk6OzUzsKYayuEi8VrWBumtwcOjBdInTYpVIj
        Hpqlx5ueD7tu8FjmS5txLbz7eQmYivFDK+cpWJkqh87mGJmGd1s4VzhCN5yGMDeL
        5ruC1WpITK/u+4//q26uv83ck068M+pdYhJs6mPZAoIBACXgeP3A/pZFPEhf25oj
        i0L6kwwKbDphGz5yNcF+VWlcK6TWalYPp++8sw48tLrm6YrM5Zvx/zLhuRh5NcP8
        f8iv0ZlhujB56ETMukPl69DHMIQUbQj6hQXlKwBXUievArsXqurYvhxumahfBQGz
        29bcl5+ovWiGi9Qasv88sQ9fiKsvy38ziHFBERNyuQemQ83SmV9556szsOVD7VLs
        O2UyKJQ4LsTn5U8P67YtQJ1SU7SblwbOF6Ehrrn01gWkSXlkszycorOy5D8Zg74q
        wO5ug4OJms51z/dwXhuBNdn9UxispR6UyScR2itkuhXszeqjxuxGq3KDYFvrQ2iT
        spECggEBAOqLJiKf4DtsDqIrsOOWwpTxI+yurkkMDmEGtaKs3mVBzTX9AmuHbTXx
        yolNiDWZ8eMKEw7ZnhrbyG9UGHzZBRMe7lfhZDkUiZv49OeZs32kdZmFvZNHIqLL
        +FBNKBmcN1zNOzU8oHN06zPm3xIzGfrGAXL8wAazh4/VliPowB2sMSHkDZ/2a/za
        ucfG/t8oCaw0r0BbOWKMwvIshE6u59augvgEGNElFN9cTje8OyF1ZdkY9/vzjJPH
        hv0sSJ+CSdf63Lz6xw5eqC19gyrao7kBcxp/D9oUdBTfOLlngjVHpD7BW67j1VbW
        ytILHlLzeV5SV4rZ6GB9NZbNGVryXOw=
        -----END PRIVATE KEY-----
      cert: |
        -----BEGIN CERTIFICATE-----
        MIIFizCCA3OgAwIBAgIJAPtDjPsjRhE4MA0GCSqGSIb3DQEBCwUAMFwxCzAJBgNV
        BAYTAlVTMQswCQYDVQQIDAJNTjELMAkGA1UEBwwCTU4xDjAMBgNVBAoMBU9wdHVt
        MQ8wDQYDVQQLDAZCRFBhYVMxEjAQBgNVBAMMCSoudWhjLmNvbTAeFw0xNzAzMDEx
        MjQ1MTZaFw0xODAzMDExMjQ1MTZaMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJN
        TjELMAkGA1UEBwwCTU4xDjAMBgNVBAoMBU9wdHVtMQ8wDQYDVQQLDAZCRFBhYVMx
        EjAQBgNVBAMMCSoudWhjLmNvbTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
        ggIBAOsDtbtvkFTQ/zOPG22gJpdF+3Omc8Qj2F61bX6SIiG9vkRdl3Dyx480Zjti
        0qlzTjnefesV3HkAL0iTGB4GA//lGPQO0uo2Xzqbd9CpGa99yHN6DCTrZ7zC7tI5
        gRfZRE3C7pX9ghR4zhbkQ9LzH6eYsDMKLByckepKlq2H0IL5D5fKuQg88NT6RoC/
        GVzn7WzQ7s4V/DCY09O2Y/yAkHpYuaUrcxClZfY3wpF+QNu8NmRb9ADbbrrODp/u
        xo4zfFxj8KiA7QAToN4P8txzrFIHX5A3dKj1q6INTvAzMkDbWjPgDKrOjBrWix5i
        VKb76nA/q3n4oJBmMKjyTMDDSdpV0HDudIecZ8VVzfFLLy1tEl4bah/SSQ/Sgqoz
        S3vz2/2aPw4tt1+q3WNMPWpeS7W32bg0i7NP8Dak+brXworMIGz9zeMYhAjsfomi
        4muS5mbpxcJZklRHv+wibxA03TIOD5NDm/87EdADblv1108ZTsr8PzEOISVu6bYL
        ZpD7YLIHAFIDO55cLXYg5FfWQbGbM+acN1Cz581XssoOVdLDwHGJ2ITpgi6urNit
        euMBhR+U87g/UoceXYLcMhPEOWRWtnXpGpKvfVVWlYa6tpBgEAIg/xMcntC8dkqt
        pW5bQpU5AQsQnhy0advk93P6zCIAn4Aq8QOnPDXWfbm7fd13AgMBAAGjUDBOMB0G
        A1UdDgQWBBT0p5WxxUqJMBj1Jd/LRlRuFE1lvzAfBgNVHSMEGDAWgBT0p5WxxUqJ
        MBj1Jd/LRlRuFE1lvzAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQAU
        k/LSFCDHuaD2mnXiefNnwNRz+L4SYxX04oAuXDiNfbRoJ1JiWPe/ZBZcoIOX9A3x
        9L3LVuV3mJTtZMd1D6jxqQStrb4hOXpI64IR+hdu12xVW+saI8GkYeePIO5P+rcN
        4QpcdVDKTA98og0J4jBmPz5pL+oZV7yR8QFTG1tT4oN/1EDhkUtUJIXHpaS9ixoD
        ejzcZNSBrnwGnYvA+xy/nnmRyVyc9I0i9A+ch8qoctMG4OnGXx6Nb/XO09VW03JR
        qsoR8yduVDiBMxhzRmq0n6C9R3dqFPTgzb1HEInwVt7gqNi0P/pZhMJ7H3GwnhZa
        V2qchsfuK9RT1FbYDzwftsN/is/0qttJ2rhB5n20P3ekIOUW2RM8xXfQJchcVA2I
        B7/T0fNY6QpxoLlG5xjy9qUbWhSlvPwKsPxDfqSeHfxoOtNFyPHRTnpDZLXDrWwJ
        gsh4aanmtIRoclCqEiE8WYI4yt1XDIxNqst0MGZgxV4UKypxkwfyOaZgHVPh+yU3
        QZgMGM5Ipv/Fq5uQHgZyIOz1HGQRQeAf9o9AIQvl+AXOS+4yM7myMpu/TJB8dkUe
        SdR6/8Z9ju1Ey3vpCbZsxl/9aytb767UUphsEY6wsIXMKlEdbto8GEgyhmpDDdd+
        hpPnDffMGsw7zsta0EcA3uR95XxfsBAdS/L+cFmwgw==
        -----END CERTIFICATE-----
    hosts: ['dbslp1404.uhc.com']
prePuller:
   hook:
     enabled: false
singleuser:
  image:
    name: docker.optum.com/bd_docid/jupyterhub
    tag: bdptf
    imagePullPolicy: Always
  cmd : start-notebook.sh
  extraLabels: {'USER':'{username}'}
  extraEnv: {'MAPR_TICKETFILE_LOCATION': '/tmp/tickets/CONTAINER_TICKET'}
  storage:
    type: None
    extraVolumes: [{ 'name': 'home',  'persistentVolumeClaim': {  'claimName': 'pvc-mapr-dlpoc-hub-svc' } }, { 'name': 'maprticket',  'secret': {  'secretName': 'dlpocid-ticket-secret' } }]
    extraVolumeMounts : [{ 'mountPath': '/maprdata', 'name': 'home'}, { 'mountPath': '/tmp/tickets/', 'name': 'maprticket'}]
