#!/usr/bin/env groovy

@Library("com.optum.jenkins.pipeline.library@v0.1.24") _

pipeline {
  agent {
    label 'docker-maven-slave'
  }
  environment {
    GIT_TOKEN = '3bce8e6d-fd79-48a9-b2d9-a7a4262bb5fa'
    TECH_USER ='oeaplatformdev'
  }

  stages {
    stage ('Build') {
      steps {
        glMavenBuild uploadJacocoResults: false, additionalProps:['ci.env':'']
      }
    }
    stage('Sonar') {
      steps {
        glSonarMavenScan gitUserCredentialsId: "${env.GIT_TOKEN}"
      }
    }
    stage('Artifactory') {
      steps {
        glMavenArtifactoryDeploy artifactoryUserCredentialsId:"${env.TECH_USER}"
      }
    }
  }
  post {
    always {
      echo 'This will always run'
      emailext body:  "Build URL: ${BUILD_URL}",
        subject: "$currentBuild.currentResult-$JOB_NAME",
        to: 'davide_savazzi@optum.com'
    }
    success {
      echo 'This will run only if successful'
    }
    failure {
      echo 'This will run only if failed'
    }
    unstable {
      echo 'This will run only if the run was marked as unstable'
    }
    changed {
      echo 'This will run only if the state of the Pipeline has changed'
      echo 'For example, if the Pipeline was previously failing but is now successful'
    }
  }
}