FROM docker.optum.com/cloudscaffolding/node:9-alpine as node
WORKDIR /app
COPY package.json /app/
RUN npm install
COPY ./ /app/
ARG env=production
RUN npm run build -- --prod --configuration $env
FROM docker.optum.com/cloudscaffolding/nginx:1.13
RUN chmod g+rwx /var/cache/nginx /var/run /var/log/nginx
RUN sed -i.bak 's/^user/#user/' /etc/nginx/nginx.conf
COPY --from=node /app/dist/ /usr/share/nginx/html
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
