apiVersion: v1
kind: Pod
metadata:
  name: pod-iscsi-lun-1-2nd 
  namespace: ns-iscsi1
spec:
  containers:
  - name: pod-iscsi-lun-1-2nd
    image: busybox
    args:
    - sleep
    - "1000000"
    volumeMounts:
    - mountPath: "/data-01"
      name: iscsipd-rw
  volumes:
  - name: iscsipd-rw
    iscsi:
      targetPortal: 10.11.182.196:3260
      portals: ['10.11.182.197:3260', '10.11.182.212:3260', '10.11.182.213:3260']
      iqn: iqn.2000-05.com.3pardata:20210002ac01d6dc
      lun: 1
      fsType: ext4
      readOnly: true
      chapAuthDiscovery: true
      chapAuthSession: true
      secretRef:
        name: chap-secret-otl3par
