apiVersion: v1
kind: Service
metadata:
   name: <service_name>
   namespace: <namespace>
   labels:
     app: <service name>
spec:
   type: NodePort
   ports:
     - port: <container Port>
   selector:
     app: <value of your app label>
