# Default values for kubeapps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
apprepository:
  syncImage:
    registry: docker.optum.com
    repository: osfi_docker/k8s-chartrepo
    tag: v1.0.0-alpha.9
  # This image is used in a Helm post-install hook to bootstrap the initialRepos below
  jobsImage:
    registry: docker.optum.com
    repository: osfi_docker/k8s-kubectl
    tag: v1.10.7
  initialRepos:
  - name: optum
    url: http://elr6hz1-01-s26.uhc.com:31080/charts
frontend:
  service:
    type: NodePort
tillerProxy:
  tls:
    ca: |
      -----BEGIN CERTIFICATE-----
     
      -----END CERTIFICATE-----
    cert: |
      -----BEGIN CERTIFICATE-----
      
      -----END CERTIFICATE-----
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      
      -----END RSA PRIVATE KEY-----
