apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      app: ose-icp-app
    name: ose-cm-connector
    namespace: ace-icp-stg
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/generated-by: OpenShiftWebConsole
        openshift.io/imported-from: 'docker.optum.com/hwoheel/ose-cm-connector:latest'
      from:
        kind: DockerImage
        name: 'docker.optum.com/hwoheel/ose-cm-connector:latest'
      generation: 1
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ose-icp-app
    name: connector
    namespace: ace-icp-stg
  spec:
    paused: true
    replicas: 0
    selector:
      app: ose-icp-app
      deploymentconfig: connector
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ose-icp-app
          deploymentconfig: connector
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: connector-configmap
          image: docker.optum.com/hwoheel/ose-cm-connector:latest
          imagePullPolicy: Always
          name: ose-cm-connector
          ports:
          - containerPort: 9299
            protocol: TCP
          - containerPort: 9399
            protocol: TCP
          - containerPort: 9499
            protocol: TCP
          - containerPort: 9599
            protocol: TCP
          - containerPort: 9699
            protocol: TCP
          - containerPort: 9799
            protocol: TCP
          - containerPort: 61616
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /usr/share/optum/icp/ImportFiles
            name: cm-connector-importfiles
          - mountPath: /usr/share/optum/icp/KB_Extracts
            name: cm-connector-kbextracts
          - mountPath: /usr/share/optum/icp/LCD_Extracts
            name: cm-connector-lcdextracts
          - mountPath: /usr/share/optum/icp/log
            name: cm-connector-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: cm-connector-importfiles
          persistentVolumeClaim:
            claimName: cm-importfiles
        - name: cm-connector-kbextracts
          persistentVolumeClaim:
            claimName: cm-kbextracts
        - name: cm-connector-lcdextracts
          persistentVolumeClaim:
            claimName: cm-lcdextracts
        - name: cm-connector-log
          persistentVolumeClaim:
            claimName: cm-log
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ose-cm-connector
        from:
          kind: ImageStreamTag
          name: 'ose-cm-connector:latest'
          namespace: ace-icp-stg
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-connector-61616
  spec:
    host: ose-cm-connector-61616-ace-icp-stg.ocp-ctc-dmz-stg.optum.com
    port:
      targetPort: 61616-tcp
    to:
      kind: Service
      name: connector-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-connector-9299
  spec:
    host: ose-cm-connector-9299-ace-icp-stg.ocp-ctc-dmz-stg.optum.com
    port:
      targetPort: 9299-tcp
    to:
      kind: Service
      name: connector-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-connector-9399
  spec:
    host: ose-cm-connector-9399-ace-icp-stg.ocp-ctc-dmz-stg.optum.com
    port:
      targetPort: 9399-tcp
    to:
      kind: Service
      name: connector-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-connector-9499
  spec:
    host: ose-cm-connector-9499-ace-icp-stg.ocp-ctc-dmz-stg.optum.com
    port:
      targetPort: 9499-tcp
    to:
      kind: Service
      name: connector-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-connector-9599
  spec:
    host: ose-cm-connector-9599-ace-icp-stg.ocp-ctc-dmz-stg.optum.com
    port:
      targetPort: 9599-tcp
    to:
      kind: Service
      name: connector-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-connector-9699
  spec:
    host: ose-cm-connector-9699-ace-icp-stg.ocp-ctc-dmz-stg.optum.com
    port:
      targetPort: 9699-tcp
    to:
      kind: Service
      name: connector-service
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ose-icp-app
    name: ose-cm-connector-9799
  spec:
    host: ose-cm-connector-9799-ace-icp-stg.ocp-ctc-dmz-stg.optum.com
    port:
      targetPort: 9799-tcp
    to:
      kind: Service
      name: connector-service
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ose-icp-app
    name: connector-service
  spec:
    ports:
    - name: 9299-tcp
      port: 9299
      protocol: TCP
      targetPort: 9299
    - name: 9399-tcp
      port: 9399
      protocol: TCP
      targetPort: 9399
    - name: 9499-tcp
      port: 9499
      protocol: TCP
      targetPort: 9499
    - name: 9599-tcp
      port: 9599
      protocol: TCP
      targetPort: 9599
    - name: 9699-tcp
      port: 9699
      protocol: TCP
      targetPort: 9699
    - name: 9799-tcp
      port: 9799
      protocol: TCP
      targetPort: 9799
    - name: 61616-tcp
      port: 61616
      protocol: TCP
      targetPort: 61616
    selector:
      deploymentconfig: connector
    sessionAffinity: None
    type: ClusterIP
  status: {}
kind: List
metadata: {}